name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    uses: raulprdev/aws-shared-hosting/.github/workflows/deploy-laravel.yml@main
    with:
      app_name: ${{ vars.APP_NAME }}
      ec2_instance_id: ${{ vars.EC2_INSTANCE_ID }}
      deploy_bucket: shared-hosting-deploy
    secrets: inherit